### ISSUE TITLE
追加［武器］ : ｋａｔａｎａ

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#23]
### 概要
- 近接武器
- 手に持っている間移動速度が上昇する

### 性能
- 攻撃力 12(仮
- 攻撃速度 未定

### タスク
- [x] 性能決定(攻撃速度
- [ ] モデル制作
- [ ] アイテムの表示制作

**Comment by Hukino** [comment]
モデルは通常の日本刀で大丈夫です。

**Comment by Kiryu-for-Kiryu** [comment]
モデルを作成してもよろしいでしょうか

**Comment by Hukino** [comment]
了解しました

**Comment by Kiryu-for-Kiryu** [comment]
完成しました
[katana.zip](https://github.com/Hukino/Sky-traveller/files/8052529/katana.zip)
![image](https://user-images.githubusercontent.com/95564353/153692292-f63a8830-ac53-4fa1-91a1-3379c5d9c3d1.png)
![image](https://user-images.githubusercontent.com/95564353/153692306-837b77b1-b63a-49d0-92bc-9c609e165727.png)

**Comment by Hukino** [comment]
いいね！
