### ISSUE TITLE
追加［魔法］：硬血

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#42]
### 概要
- 防御力が高くなる代わりにHP回復速度が遅くなる。
- 光属性の魔法
- 血のような赤色をした結晶の塊

### 性能
消費MP 40

### タスク
- [x] アイテムのテクスチャを制作
- [x] 本効果を作成
- [x] インベントリ内のアイテムの見た目を制作。

**Comment by Kiryu-for-Kiryu** [comment]
テクスチャ作成してもよろしいでしょうか

**Comment by Hukino** [comment]
おｋ

**Comment by Kiryu-for-Kiryu** [comment]
どうでしょうか
![koketsu](https://user-images.githubusercontent.com/95564353/148347834-96f95aad-709c-45b0-92f3-953aee974c50.png)
![koketsu](https://user-images.githubusercontent.com/95564353/148347887-0fdf14e8-2326-43e9-94ee-233a5bf2f5cf.png)

**Comment by Hukino** [comment]
いいよ！

**Comment by Hukino** [comment]
作成したよ！
