### ISSUE TITLE
追加［防具］：ヴァイキングの帽子

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#47]
### 概要
- 角のついた帽子

### 性能
- 棘Ⅰ

### タスク
- [x] モデル制作
- [x] 効果制作

**Comment by Kiryu-for-Kiryu** [comment]
モデルを作成します

**Comment by Kiryu-for-Kiryu** [comment]
ファイルと見た目です。ディスプレイは設定はすでにに完了済みです。
[vaiking_hat.zip](https://github.com/Hukino/Sky-traveller/files/7912086/vaiking_hat.zip)
![image](https://user-images.githubusercontent.com/95564353/150503828-31d7db0d-9417-48cc-8e97-5712693d60f6.png)

**Comment by Hukino** [comment]
了解です
