### ISSUE TITLE
追加［武器］ : 鰹節

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#5]
### 概要
- 近接武器
- 持っている間防御力1.2倍

### 性能
- 攻撃力 10
- 有効距離 0.9
- 攻撃速度 5

### タスク
- [x] モデル制作
- [x] アイテムの表示制作

**Comment by zinn6118** [comment]
鰹節描きます

**Comment by Hukino** [comment]
おｋ！

**Comment by zinn6118** [comment]
![katuo](https://user-images.githubusercontent.com/69614928/148352317-6216b57c-093f-41d8-8d42-2ce14c73d5ea.png)

**Comment by Hukino** [comment]
制作が完了しました
