### ISSUE TITLE
追加［アクセサリー］：赤鬼鉄鎖

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#50]
### 概要
- 赤黒い鉄の足枷

### 性能
- 移動速度-20%
- 与えたダメージの四分の一回復

### タスク
- [x] アイテムテクスチャ/モデル制作
- [x] アイテムの表示制作

**Comment by zinn6118** [comment]
描いてもよろしいでしょうか

**Comment by Hukino** [comment]
承認！

**Comment by zinn6118** [comment]
![sekiii](https://user-images.githubusercontent.com/69614928/151665061-3de35f62-db9f-4ad0-a29d-08f16ed120d0.png)

**Comment by Hukino** [comment]
なんて早さだ...受けとりました！
