### ISSUE TITLE
追加［アクセサリー］：廻る奇石

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#54]
### 概要
- 血管が張り巡らされているようにも見える黄金の石

### 性能
- mp回復速度＋5％

### タスク
- [x] アイテムテクスチャ/モデル制作
- [x] アイテムの表示制作

**Comment by zinn6118** [comment]
描いてもよろしいでしょうか

**Comment by Hukino** [comment]
いいよ！

**Comment by zinn6118** [comment]
![kiseki](https://user-images.githubusercontent.com/69614928/151664818-9dce57c5-7dd0-436e-b0aa-15b51a6dba13.png)

**Comment by Hukino** [comment]
仕事が早いぜ！ありがとう！

**Comment by Hukino** [comment]
追加したよん
