### ISSUE TITLE
追加［武器］ : バンクナイフ

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#6]
### 概要
- 近接武器
- 所持金を消費して強化できる
- 手に持っている間金のゲット量1.2倍

### 性能
- 攻撃力 7
- 強化時 14
- 有効距離 1.2
- 攻撃速度 2

### タスク
- [x] モデル制作
- [x] アイテムの表示制作

**Comment by Hukino** [comment]
作り終わったよ
