### ISSUE TITLE
追加［アクセサリー］：パワーストーン

### ISSUE THREAD

**Issue by zinn6118** [Hukino/Sky-traveller#68]
### 概要
- 指輪

### 性能
- 表記上は不明だが実際の効果は無し

### タスク
- [x] アイテムテクスチャ/モデル制作
- [ ] アイテムの表示制作

**Comment by Hukino** [comment]
![image](https://user-images.githubusercontent.com/79348353/159225893-d05e43a2-9c62-4f2a-9077-5c5e13ec1862.png)
アイテムのテクスチャです。

**Comment by Hukino** [comment]
完成したよ
